# Generated by Django 4.1.7 on 2023-05-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('SNAME', models.CharField(max_length=100)),
                ('SID', models.IntegerField(primary_key=True, serialize=False)),
                ('SADDRESS', models.TextField(max_length=200)),
            ],
        ),
    ]
